### ISSUE TITLE
docker image from documentation seems to be unavailable

### ISSUE THREAD

**Issue by xwrs** [the-guild-org/conductor#483]
when trying to pull in docker-compose using image from documentation `the-guild-org/conductor:latest` is not found at all. tried to crawl your pipelines and tried using: `ghcr.io/the-guild-org/conductor:latest` still with no luck

```
 ✘ conductor Error                                                                                                                  0.7s 
Error response from daemon: Head "https://ghcr.io/v2/the-guild-org/conductor/manifests/latest": denied
```

only way was to obtain correct image path from the pipelines from one of last builds here https://github.com/the-guild-org/conductor/actions/runs/8100553894/job/22138827930#step:7:22

still struggling with a quick start guideline but the product seems really promising. couldn't wait to get subscriptions support ready. will try to hold myself from making PRs :)

**Comment by dotansimha** [comment]
Thanks @xwrs ! I think we might have an issue with the `latest` tag? Because it seems like using the commit id as a Docker tag does work?

**Comment by dotansimha** [comment]
Done in https://github.com/the-guild-org/conductor/commit/a474fcf7e0659b12fbe808043baff65cfc3e97a1
