### ISSUE TITLE
Are the cargo crates released to crates.io?

### ISSUE THREAD

**Issue by github2023spring** [the-guild-org/conductor#604]
Are the cargo crates released to crates.io? If no, is there a plan for releasing it to crates.io? Thank you!

**Comment by YassinEldeeb** [comment]
Hey, the crates are not released, we have no reason to release them on crates.io at the moment, but if you need any of the modules, you can fork the repo, copy and paste the crates into your project directly or publish the crates on your own crates.io account, everything is MIT, so anything here is yours too :)
